/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 15 03:55:36 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Die;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Die_ESTest extends Die_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. <init>(II)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 2. [METHOD] edu.osu.cs362.Die.<init>(II)V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Die die0 = null;
      try {
        die0 = new Die((-33), (-33));
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. <init>(I)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 2. [METHOD] edu.osu.cs362.Die.<init>(I)V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Die die0 = null;
      try {
        die0 = new Die(0);
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * Goal 1. edu.osu.cs362.Die.<init>()V: root-Branch
   * Goal 2. <init>()V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 3. [METHOD] edu.osu.cs362.Die.<init>()V
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Die die0 = null;
      try {
        die0 = new Die();
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 3
  /*
   * 3 covered goals:
   * Goal 1. edu.osu.cs362.Die.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. main([Ljava/lang/String;)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 3. [METHOD] edu.osu.cs362.Die.main([Ljava/lang/String;)V
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Die.main((String[]) null);
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
